db:
  image: mysql:5.6.34
  ports:
    - "3308:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=dev

web:
  build: .
  command: /bin/bash -l -c "bundle update i18n && rake db:migrate && ./bin/runner"
  ports:
    - "9092:9092"
  links:
    - db
